import Head from "next/head";
import ConnectClients from "../components/connect-clients";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ably test home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>Aaaaa</div>

      <ConnectClients />
    </div>
  );
}
