import dynamic from "next/dynamic";
import Head from "next/head";

const ConnectClients = dynamic(() => import("../components/connect-clients"), {
  ssr: false,
});

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ably test home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-screen h-screen p-4">
        <ConnectClients />
      </div>
    </div>
  );
}
